apiVersion: v1
kind: Service
metadata:
  name: customer-service-node
  labels:
    app: customer-service-node
spec:
  type: NodePort
  selector:
    app: customer-service-node
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
